CREATE DATABASE AQUAPEDIA;

USE AQUAPEDIA;

CREATE TABLE USUARIOS (
  USR_EMAIL VARCHAR(60),
  USR_SENHA VARCHAR(255),
  USR_PROGRESSO INT DEFAULT 1,
  USR_FOTO INT DEFAULT 0,
  USR_NOME VARCHAR(30),
  USR_ID INT AUTO_INCREMENT PRIMARY KEY,
  UNIQUE(USR_EMAIL, USR_NOME, USR_ID)
);